### ISSUE TITLE
Adicionar protocolo https para nosso dominio

### ISSUE THREAD

**Issue by andreluizpd** [baduk-corp/KudabCoach#15]
Precisamos de um certificado para uso de https em nosso domino, assim ficando mais fail de encontrá-lo em buscas e o deixando com mais credibilidade para o usuário

**Comment by andreluizpd** [comment]
@Fhagemeier Pode verificar isso ?

**Comment by Fhagemeier** [comment]
Adicionado com o lets encrypt 
https://certbot.eff.org/lets-encrypt/debianstretch-apache
